 services:
    - type: web
      name: aircraft-prediction-api
      env: python
      region: oregon
      buildCommand: pip install -r backend/requirements.txt
      startCommand: cd backend && gunicorn app:app
      envVars:
        - key: PYTHON_VERSION
          value: 3.11.0